repeat_last_feeding:
  name: Repeat Last Feeding
  description: Repeats last feeding.
  target:
    entity:
      integration: smartfeed
      domain: switch

feed:
  name: Feed
  description: Feeds the pet.
  target:
    entity:
      integration: smartfeed
      domain: switch
  fields:
    amount:
      description: Amount to feed in 1/8 cup increments
      example: 12
